package org.example;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.EntityTransaction;
import jakarta.persistence.Persistence;
import org.example.entities.Client;
import org.example.entities.Rent;
import org.example.entities.Vehicle;
import org.example.entities.vehicles.Bicycle;
import org.example.entities.vehicles.Car;
import org.example.exceptions.RentalException;
import org.example.repositories.ClientRepository;
import org.example.repositories.RentRepository;
import org.example.repositories.VehicleRepository;
import org.example.services.RentService;
import org.example.util.Address;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;


public class Main {
    private static final Logger logger = LoggerFactory.getLogger(Main.class);
    private static final Random random = new Random();

    public static void main(String[] args) {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("default");

        try {
            logger.info("Starting database population...");

            // Create repositories and service
            EntityManager em = emf.createEntityManager();
            ClientRepository clientRepository = new ClientRepository(em);
            VehicleRepository vehicleRepository = new VehicleRepository(em);
            RentRepository rentRepository = new RentRepository(em);
            RentService rentService = new RentService(emf, clientRepository, vehicleRepository, rentRepository);

            List<Client> clients = createAndSaveClients(em, clientRepository);
            List<Vehicle> vehicles = createAndSaveVehicles(em, vehicleRepository);
            createAndSaveRents(emf, rentService, rentRepository, clients, vehicles);

            em.close();
            logger.info("Database population completed successfully!");

            System.out.print("Press any key to continue...");
            new Scanner(System.in).nextLine();

        } catch (Exception e) {
            logger.error("Error during database population: ", e);
        } finally {
            emf.close();
        }
    }

    // Method generated by Claude Opus 4.1
    private static List<Client> createAndSaveClients(EntityManager em, ClientRepository clientRepository) {
        List<Client> clients = new ArrayList<>();
        EntityTransaction transaction = em.getTransaction();

        // Polish names and addresses
        String[] firstNames = {
                "Adam", "Piotr", "Krzysztof", "Andrzej", "Tomasz",
                "Paweł", "Michał", "Marcin", "Marek", "Grzegorz",
                "Anna", "Maria", "Katarzyna", "Małgorzata", "Agnieszka",
                "Barbara", "Ewa", "Elżbieta", "Zofia", "Teresa"
        };

        String[] lastNames = {
                "Nowak", "Kowalski", "Wiśniewski", "Wójcik", "Kowalczyk",
                "Kamiński", "Lewandowski", "Zieliński", "Szymański", "Woźniak",
                "Dąbrowski", "Kozłowski", "Jankowski", "Mazur", "Kwiatkowski",
                "Krawczyk", "Piotrowski", "Grabowski", "Pawłowski", "Michalski"
        };

        String[] streets = {
                "Piotrkowska", "Pomorska", "Wolności", "Legionów", "Sienkiewicza",
                "Mickiewicza", "Kościuszki", "Piłsudskiego", "Narutowicza", "Żeromskiego"
        };

        String[] cities = {
                "Łódź", "Warszawa", "Kraków", "Wrocław", "Poznań",
                "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Katowice"
        };

        try {
            transaction.begin();

            for (int i = 0; i < 20; i++) {
                String firstName = firstNames[i];
                String lastName = lastNames[i];
                String personalId = generatePolishPesel();

                Address address = new Address(
                        streets[random.nextInt(streets.length)],
                        String.valueOf(random.nextInt(200) + 1),
                        cities[random.nextInt(cities.length)],
                        String.format("%02d-%03d", random.nextInt(99), random.nextInt(999))
                );

                Client client = new Client(personalId, firstName, lastName, address);

                // Set random maxVehicles between 1 and 4
                client.setMaxVehicles(random.nextInt(4) + 1);

                // Some clients have higher spending (for discount calculation)
                if (i < 5) {
                    client.addMoneySpent(random.nextInt(30000) + 10000);
                }

                client = clientRepository.save(client);
                clients.add(client);
                logger.info("Created client: {} {} (ID: {})", firstName, lastName, client.getId());
            }

            transaction.commit();
            logger.info("Successfully saved {} clients", clients.size());

        } catch (Exception e) {
            if (transaction.isActive()) {
                transaction.rollback();
            }
            logger.error("Error creating clients: ", e);
            throw e;
        }

        return clients;
    }

    // Method generated by Claude Opus 4.1
    private static List<Vehicle> createAndSaveVehicles(EntityManager em, VehicleRepository vehicleRepository) {
        List<Vehicle> vehicles = new ArrayList<>();
        EntityTransaction transaction = em.getTransaction();

        try {
            transaction.begin();

            // Create 7 cars
            String[] carPlates = {
                    "EL234GH", "WA789KL", "KR456MN", "PO123AB",
                    "GD987ZX", "LU654QW", "KT321ER"
            };

            Car.SegmentType[] segments = Car.SegmentType.values();

            for (int i = 0; i < 7; i++) {
                double engineDisplacement = 1.0 + (random.nextDouble() * 2.5); // 1.0 to 3.5
                double perHourPrice = 20.0 + (random.nextDouble() * 80.0); // 20 to 100 PLN
                Car.SegmentType segment = segments[random.nextInt(segments.length)];

                Car car = new Car(carPlates[i], perHourPrice,
                        Math.round(engineDisplacement * 10) / 10.0, segment);

                car = vehicleRepository.save(car);
                vehicles.add(car);
                logger.info("Created car: {} (Segment: {}, Engine: {}L, Price: {} PLN/h)",
                        car.getPlateNumber(), segment, car.getEngineDisplacement(), car.getPerHourPrice());
            }

            // Create 3 bicycles
            String[] bikePlates = {"BK30011LD", "BL33002WR", "BW54003KR"};

            for (String plate : bikePlates) {
                double perHourPrice = 5.0 + (random.nextDouble() * 15.0); // 5 to 20 PLN

                Bicycle bicycle = new Bicycle(plate, Math.round(perHourPrice * 100) / 100.0);
                bicycle = vehicleRepository.save(bicycle);
                vehicles.add(bicycle);
                logger.info("Created bicycle: {} (Price: {} PLN/h)",
                        bicycle.getPlateNumber(), bicycle.getPerHourPrice());
            }

            transaction.commit();
            logger.info("Successfully saved {} vehicles", vehicles.size());

        } catch (Exception e) {
            if (transaction.isActive()) {
                transaction.rollback();
            }
            logger.error("Error creating vehicles: ", e);
            throw e;
        }

        return vehicles;
    }

    // Method generated by Claude Opus 4.1
    private static void createAndSaveRents(EntityManagerFactory emf, RentService rentService,
                                           RentRepository rentRepository,
                                           List<Client> clients, List<Vehicle> vehicles) {
        logger.info("Creating rentals...");

        LocalDateTime now = LocalDateTime.now();
        int successfulRentals = 0;
        int completedRentals = 0;

        // Create 15 rentals
        for (int i = 0; i < 15; i++) {
            Client client = clients.get(random.nextInt(clients.size()));
            Vehicle vehicle = vehicles.get(random.nextInt(vehicles.size()));

            // Generate random start time in the last 30 days
            LocalDateTime beginTime = now.minusDays(random.nextInt(30))
                    .minusHours(random.nextInt(24))
                    .truncatedTo(ChronoUnit.HOURS);

            try {
                // Create rental
                Rent rent = rentService.rentVehicle(client.getId(), vehicle.getId(), beginTime);
                successfulRentals++;

                logger.info("Created rental #{}: Client {} {} rented {} starting at {}",
                        rent.getId(),
                        client.getFirstName(),
                        client.getLastName(),
                        vehicle.getPlateNumber(),
                        beginTime);

                // 60% chance to complete the rental
                if (random.nextDouble() < 0.6) {
                    // Generate end time (1-72 hours after start)
                    LocalDateTime endTime = beginTime.plusHours(random.nextInt(72) + 1);

                    // Make sure end time is not in the future
                    if (endTime.isAfter(now)) {
                        endTime = now.minusHours(1);
                    }

                    try {
                        rent = rentService.endRental(rent.getId(), endTime);
                        completedRentals++;
                        logger.info("Completed rental #{}: Total cost: {} PLN",
                                rent.getId(),
                                String.format("%.2f", rent.getTotalCost()));
                    } catch (RentalException e) {
                        logger.warn("Could not complete rental #{}: {}", rent.getId(), e.getMessage());
                    }
                }

            } catch (RentalException e) {
                logger.warn("Could not create rental for client {} and vehicle {}: {}",
                        client.getLastName(), vehicle.getPlateNumber(), e.getMessage());
            }
        }

        logger.info("Created {} rentals ({} completed, {} active)",
                successfulRentals, completedRentals, successfulRentals - completedRentals);
    }

    // Method generated by Claude Opus 4.1
    private static String generatePolishPesel() {
        // Generate a valid-looking PESEL number (Polish national ID)
        // Format: YYMMDDXXXXX (year, month, day, serial number, control digit)
        int year = 70 + random.nextInt(30); // 1970-1999
        int month = random.nextInt(12) + 1;
        int day = random.nextInt(28) + 1;
        int serial = random.nextInt(9999);
        int control = random.nextInt(9);

        return String.format("%02d%02d%02d%04d%d", year, month, day, serial, control);
    }
}